services:
  backend:
    image: ${ECR_BACKEND_IMAGE}
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ${ECR_FRONTEND_IMAGE}
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
