data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]

  # "al2023-ami-*-x86_64" also matches the *minimal* variant
  # (al2023-ami-minimal-2023.12...), which was actually being selected as
  # "most recent" - and the minimal image doesn't ship the SSM Agent at all,
  # which is why CD's SSM deploy step kept failing with no explanation:
  # nothing was misconfigured, the agent binary simply didn't exist on the
  # instance. "al2023-ami-2*" matches only the standard variant (name starts
  # with the year, not "minimal-").
  filter {
    name   = "name"
    values = ["al2023-ami-2*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- SSH key pair ------------------------------------------------------------
# Generated by Terraform (app-internal cryptographic material, not a
# third-party credential) so Muneera can SSH in for debugging if needed.
# Private key saved locally, git-ignored, never committed.

resource "tls_private_key" "ec2" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "ec2" {
  key_name   = "autoassist-ec2-key"
  public_key = tls_private_key.ec2.public_key_openssh
}

resource "local_sensitive_file" "ec2_private_key" {
  content         = tls_private_key.ec2.private_key_pem
  filename        = "${path.module}/autoassist-ec2-key.pem"
  file_permission = "0600"
}

# --- IAM role for the EC2 instance --------------------------------------------
# Instance role, not static access keys baked into the instance — the whole
# point of this pattern (see HANDOFF.md's discussion of autoassist-dev vs.
# autoassist-terraform for the same reasoning applied one level down: the
# deployed app's own runtime identity shouldn't be the same as anything used
# to provision infrastructure, and shouldn't be static keys at all when an
# instance role can do the job with automatic credential rotation).

resource "aws_iam_role" "ec2" {
  name = "autoassist-ec2-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action    = "sts:AssumeRole"
        Effect    = "Allow"
        Principal = { Service = "ec2.amazonaws.com" }
      }
    ]
  })
}

# Required for CD's SSM Run Command deploy to work at all — separate from
# the GitHub Actions role's ssm:SendCommand permission (which controls who
# can *issue* commands), this is what lets the SSM Agent already running on
# the instance register itself as a "managed instance" SSM knows about in
# the first place. Missing this caused "InvalidInstanceId: Instances not in
# a valid state for account" on the first real CD deploy attempt — found
# once the OIDC/DescribeInstances issues were already fixed and this was
# the next thing blocking the checkpoint.
resource "aws_iam_role_policy_attachment" "ec2_ssm" {
  role       = aws_iam_role.ec2.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_role_policy" "ec2_ses" {
  name = "autoassist-ec2-ses-policy"
  role = aws_iam_role.ec2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["ses:SendEmail", "ses:SendRawEmail"]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_role_policy" "ec2_s3" {
  name = "autoassist-ec2-s3-policy"
  role = aws_iam_role.ec2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["s3:PutObject", "s3:GetObject"]
        Resource = "arn:aws:s3:::${var.s3_receipts_bucket}/*"
      }
    ]
  })
}

resource "aws_iam_role_policy" "ec2_ecr" {
  name = "autoassist-ec2-ecr-policy"
  role = aws_iam_role.ec2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = "ecr:GetAuthorizationToken"
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = ["ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer", "ecr:BatchCheckLayerAvailability"]
        Resource = [
          "arn:aws:ecr:${var.aws_region}:224603709350:repository/autoassist-backend",
          "arn:aws:ecr:${var.aws_region}:224603709350:repository/autoassist-frontend",
        ]
      }
    ]
  })
}

# Phase 9: lets user_data publish this instance's current public IP so the
# reminders Lambda (which doesn't run on the instance, so can't use IMDS)
# can find the backend without a hardcoded, destroy/apply-cycle-stale IP.
resource "aws_iam_role_policy" "ec2_ssm_parameter" {
  name = "autoassist-ec2-ssm-parameter-policy"
  role = aws_iam_role.ec2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["ssm:PutParameter"]
        Resource = "arn:aws:ssm:${var.aws_region}:224603709350:parameter${var.backend_url_param}"
      }
    ]
  })
}

resource "aws_iam_instance_profile" "ec2" {
  name = "autoassist-ec2-profile"
  role = aws_iam_role.ec2.name
}

# --- EC2 instance --------------------------------------------------------------

resource "aws_instance" "app" {
  ami                    = data.aws_ami.amazon_linux.id
  instance_type          = var.instance_type
  subnet_id              = aws_subnet.public[0].id
  vpc_security_group_ids = [aws_security_group.ec2.id]
  iam_instance_profile   = aws_iam_instance_profile.ec2.name
  key_name               = aws_key_pair.ec2.key_name

  # Without this, a user_data edit + plain `apply` just stops/restarts the
  # SAME instance to update the stored attribute - cloud-init recognizes the
  # unchanged instance ID as already-initialized and skips re-running
  # user_data entirely, so the edit never actually executes. Root-caused a
  # live Phase 9 outage where a user_data fix silently never took effect.
  user_data_replace_on_change = true

  # This AMI's default root volume is only 2GB - nowhere near enough once
  # Docker is pulling two real images plus OS overhead. Hit "no space left
  # on device" mid-pull on first apply after switching to the ECR-based
  # deploy; 20GB gives real headroom without meaningfully changing cost
  # (gp3 is ~$0.08/GB-mo, so this is under $2/mo).
  root_block_device {
    volume_size = 20
    volume_type = "gp3"
  }

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    deploy_bucket      = var.s3_receipts_bucket
    aws_region         = var.aws_region
    # urlencode'd because db_password is random-generated and can contain
    # characters like "/" or "@" that break DATABASE_URL's connection-string
    # parsing when interpolated raw (root-caused a live Phase 9 outage where
    # a generated password contained "/").
    db_password        = urlencode(var.db_password)
    rds_endpoint       = aws_db_instance.main.endpoint
    jwt_secret_key     = var.jwt_secret_key
    ses_sender_email   = var.ses_sender_email
    s3_bucket_name     = var.s3_receipts_bucket
    ecr_backend_image  = "${var.ecr_backend_repository_url}:latest"
    ecr_frontend_image = "${var.ecr_frontend_repository_url}:latest"
    ecr_registry       = "224603709350.dkr.ecr.${var.aws_region}.amazonaws.com"
    internal_api_key   = var.internal_api_key
    backend_url_param  = var.backend_url_param
  })

  tags = {
    Name = "autoassist-app"
  }
}
